version: 0.1
log:
  level: debug
  fields:
    service: registry
    environment: production
storage:
  cache:
    layerinfo: inmemory
  filesystem:
    rootdirectory: /registry
common:
  search_backend: sqlalchemy
  sqlalchemy_index_database: sqlite:////registry/docker-registry.db
http:
  addr: :5000
  secret: {bash some random characters here}
